idle_bg = "#313244"
idle_fg = "#cdd6f4"
info_bg = "#313244"
info_fg = "#89b4fa"
good_bg = "#313244"
good_fg = "#a6e3a1"
warning_bg = "#313244"
warning_fg = "#f9e2af"
critical_bg = "#313244"
critical_fg = "#f38ba8"
separator = "\ue0b4 \ue0b6"
separator_bg = "#1e1e2e"
separator_fg = "auto"
