[theme]
background = "#1E1E2F"
primary = "#CAD3F5"
secondary = "#C6A0F6"
title = "#F5BDE6"
playing = "#A6DA95"
playing_selected = "#F5A97F"
playing_bg = "#2C3239"
highlight = "#CAD3F5"
highlight_bg = "#45475B"
error = "#ED8796"
error_bg = "#181926"
statusbar = "#A6DA95"
statusbar_progress = "#A6DA95"
statusbar_bg = "#2C3239"
cmdline = "#B7BDF8"
cmdline_bg = "#181926"
